version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: make build-api
  test:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test