[server]
port = 5005
debug_mode = true
tls_disable = true
tls_cert_file = "./dev-keys/tls.crt"
tls_key_file = "./dev-keys/tls.key"

[database]
address = "localhost:42333"
username = "root"
password = "root"
