[server]
port = ":5005"
log_level = "debug"
tls_disable = true
tls_cert_file = "./dev-keys/tls.crt"
tls_key_file = "./dev-keys/tls.key"

[database]
address = "localhost:3306"
username = "root"
password = "root"
