[server]
port = 5005
debug_mode = false
tls_disable = true
tls_cert_file = "./dev-keys/tls.crt"
tls_key_file = "./dev-keys/tls.key"

[database]
address = "localhost:42333"
username = "root"
password = "root"

[auth]
disable = false
expiry = 168
private_key_type = "file" # "file" only type currently supported
private_key = "auth/keys/devRSA.key"
public_key = "auth/keys/devRSA.key.pub"