version: "3"

services:
  db:
    image: mariadb:10.4.1
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quirkdb
    ports:
      - '3306:3306'